// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scot.Services.ProductAPI.DbContexts;

#nullable disable

namespace Scot.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220316225436_SeedProduct")]
    partial class SeedProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Scot.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Meal",
                            Description = "Tipycal Scottish meal. From Highlands",
                            ImageUrl = "https://microserviceproject.blob.core.windows.net/scot/haggis.jpg",
                            Name = "Haggis",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Meal",
                            Description = "Another typical scottish meal. From... well, could be anywhere :D",
                            ImageUrl = "https://microserviceproject.blob.core.windows.net/scot/mac-and-cheese.png",
                            Name = "Mac & Cheese",
                            Price = 14.75
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Meal",
                            Description = "Pizza with cheese, tomato, basil and haggis. Yum yum!",
                            ImageUrl = "https://microserviceproject.blob.core.windows.net/scot/pizza_haggis.png",
                            Name = "Pizza with Haggis",
                            Price = 10.25
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Meal",
                            Description = "Directly from her Majesty The Queen, the biggest hamburger! Only for faggots",
                            ImageUrl = "https://microserviceproject.blob.core.windows.net/scot/royal_hamburger.jpg",
                            Name = "Royal Hamburger",
                            Price = 16.890000000000001
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Side",
                            Description = "French. Fries.",
                            ImageUrl = "https://microserviceproject.blob.core.windows.net/scot/French_Fries.jpg",
                            Name = "French fries",
                            Price = 6.5499999999999998
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Side",
                            Description = "Mixture of Snacks",
                            ImageUrl = "https://microserviceproject.blob.core.windows.net/scot/snacks.jpg",
                            Name = "Snaks",
                            Price = 3.9500000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
